site_name: Ricardo B. Sousa Personal Webpage
site_url: https://sousarbarb.github.io/
# site_url: https://127.0.0.1:10000

plugins:
  - search

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme)"
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  # generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sousarbarb/
      name: GitHub @sousarbarb
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/sousarbarb/
      name: GitLab @sousarbarb
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.inesctec.pt/ricardo.b.sousa/
      name: GitLab INESC TEC @sousarbarb
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0003-4537-5095/
      name: ORCiD
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sousa-ricardob/
      name: LinkedIn
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sousarbarb97/
      name: Instagram
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/sousarbarb97/
      name: Reddit
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCXTR8mMlG0VOC_06PKg5KBQ/
      name: YouTube Channel @RicardoBSousa

nav:
  - Home: index.md
  - CV: cv.md
  - Research: research.md
  - Projects: projects.md
  - Teaching: teaching.md
  - Publications: publications.md
  - Open-Source: open-source.md
  - Awards: awards.md
  - Robotics: robotics.md
  - Tools: tools.md

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
