site_name: Ricardo B. Sousa Personal Webpage
site_url: https://sousarbarb.github.io/
site_author: Ricardo B. Sousa

# Repository
repo_name: sousarbarb/sousarbarb.github.io
repo_url: https://github.com/sousarbarb/sousarbarb.github.io
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2022 Ricardo B. Sousa

plugins:
  - search

theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: sousarbarb
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Red Hat Text
    code: JetBrains Mono
  favicon: assets/logo/sousarbarb_penguin_logo_0-padding.svg
  logo: assets/logo/sousarbarb_penguin_logo_white_0-padding.svg

# Additional configuration
extra:
  # generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sousarbarb/
      name: GitHub @sousarbarb
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/sousarbarb/
      name: GitLab @sousarbarb
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.inesctec.pt/ricardo.b.sousa/
      name: GitLab INESC TEC @sousarbarb
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0003-4537-5095/
      name: ORCiD
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.pt/citations?user=Bz2FMqYAAAAJ
      name: Google Scholar
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sousa-ricardob/
      name: LinkedIn
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCXTR8mMlG0VOC_06PKg5KBQ/
      name: YouTube Channel @RicardoBSousa

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.pathconverter:
      base_path: "sousarbarb/sousarbarb.github.io"
      relative_path: ""
      absolute: false

nav:
  - Home: index.md
  - CV: cv.md
  - Research: research.md
  - Projects: projects.md
  - Teaching: teaching.md
  - Publications: publications.md
  - Open-Source: open-source.md
  - Awards: awards.md
  - Robotics: robotics.md
  - Tools:
      - tools/index.md
      - Operating System (OS):
          - tools/os/index.md
          - NVIDIA Drivers: tools/os/nvidia.md
          - Remote Access: tools/os/remote-access.md
          - Development Environment: tools/os/dev.md
      - Git: tools/git.md
      - Docker:
          - tools/docker/index.md

extra_javascript:
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css
